language: python
python:
  - "3.6"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda env create -q -f env_cpu.yml
  - conda activate amptorch
  - pip install python-coveralls
  - pip install coverage
  - pip install -e .

script:
  #- coverage run ./amptorch/tests/test_script.py
  - python ./amptorch/tests/test_script.py

#after_success:
  #- coveralls
