language: python
env:
  - export PYTHONPATH=/amptorch:$PYTHONPATH      
os:
  - linux
rvm:
  - 3.6
addons:
  apt:
    packages:
    - gfortran
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install skorch
  - pip install git+https://github.com/mshuaibii/SIMPLE-NN
  - pip install git+https://bitbucket.org/andrewpeterson/amp.git
  - pip install spglib
  - pip install torch
  - pip install ase
  - pip install scipy
  - pip install .
script:
  - coverage run ./amptorch/tests/test_script.py 
after_success:
  - coveralls
